# Generated by Django 4.2.7 on 2025-02-01 08:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('answer_en', ckeditor.fields.RichTextField()),
                ('question_hi', models.TextField(blank=True)),
                ('question_bn', models.TextField(blank=True)),
            ],
        ),
    ]
