version: '3'

services:
  web:
    build: .
    container_name: faq_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=faq_project.settings

  redis:
    image: redis:alpine
    container_name: faq_redis
    restart: always
    ports:
      - "6379:6379"
